#!/usr/bin/env bash

SITEID=${1?Error: no site ID given}
echo "Configuring $SITEID edge device"

swupd update
reboot
swupd bundle-add network-basic
swupd bundle-add containers-basic
swupd bundle-add vim-minimal
swupd bundle-add ansible
systemctl mask $(sed -n -e 's#^/dev/\([0-9a-z]*\).*#dev-\1.swap#p' /proc/swaps) 2>/dev/null
swapoff -a
reboot
-s
mkdir -p /etc/sysctl.d/
tee /etc/sysctl.d/60-k8s.conf > /dev/null <<EOF
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF
systemctl restart systemd-sysctl
nmcli connection modify "Wired connection 1" \
ipv4.method "manual" \
ipv4.addresses "192.168.0.20/24" \
ipv4.gateway "192.168.0.1" \
ipv4.dns "8.8.8.8,1.1.1.1"
systemctl restart NetworkManager
reboot
-s
echo "127.0.0.1 localhost `hostname`" | sudo tee --append /etc/hosts
exit
swupd autoupdate --disable
reboot
mkdir /usr/local/bin
curl -sfL https://get.k3s.io | sh -
systemctl status k3s
echo "$SITEID edge device successfully configured!"

